CREATE TABLE persons(
	Id INT(10) UNASIGNED NULL DEFAULT NULL,
	FirstName VARCHAR(50) NULL DEFAULT NULL,
	LastName VARCHAR(50) NULL DEFAULT NULL,
	Address VARCHAR(50) NULL DEFAULT NULL,
	Gender VARCHAR(50) NULL DEFAULT NULL
)
ENGINE=INNODB
;

